// src/lib/mockData.ts
import {
  Tenant,
  Branch,
  Category,
  Brand,
  Product,
  Customer,
  Lead,
  QuoteRequest,
  Quote,
  FAQItem,
  Testimonial,
  GalleryItem,
  OfferItem,
  IndustryItem,
  ServiceItem,
  AuditLog,
} from '@/types';

export const mockTenant: Tenant = {
  id: 'tenant-frostflow-01',
  name: 'FrostFlow Engineering',
  slug: 'frostflow',
  tagline: 'Demo Concept for Commercial Refrigeration Businesses',
  logo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=200&auto=format&fit=crop',
  currency: 'INR',
  currencySymbol: '₹',
  defaultTaxRate: 0.18,
  createdAt: '2026-01-01T00:00:00.000Z',
  deletedAt: null,
  branches: [
    {
      id: 'branch-mumbai-hq',
      tenantId: 'tenant-frostflow-01',
      name: 'Mumbai Experience Center (Demo)',
      code: 'BOM-MAIN',
      address: 'Commercial Equipment Showroom Zone',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      phone: '+91 XXX XXX XXXX',
      whatsapp: '917702256073',
      email: 'sales@frostflow.com',
      coordinates: { lat: 19.1136, lng: 72.8697 },
      operatingHours: 'Mon - Sat: 9:30 AM - 7:30 PM',
      isMainBranch: true,
      servicesOffered: ['Full Showroom Display', 'Cold Room Demo Lab', 'AMC Servicing Hub'],
      createdAt: '2026-01-01T00:00:00.000Z',
      deletedAt: null,
    },
    {
      id: 'branch-blr-hub',
      tenantId: 'tenant-frostflow-01',
      name: 'Bengaluru Regional Center (Demo)',
      code: 'BLR-SOUTH',
      address: 'Industrial Equipment Corridor',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      phone: '+91 XXX XXX XXXX',
      whatsapp: '917702256073',
      email: 'bangalore@frostflow.com',
      coordinates: { lat: 12.9352, lng: 77.6245 },
      operatingHours: 'Mon - Sat: 10:00 AM - 8:00 PM',
      isMainBranch: false,
      servicesOffered: ['Restaurant Equipment Consultation', 'Bakery Case Display'],
      createdAt: '2026-01-15T00:00:00.000Z',
      deletedAt: null,
    },
    {
      id: 'branch-delhi-ncr',
      tenantId: 'tenant-frostflow-01',
      name: 'Delhi NCR Experience Hub (Demo)',
      code: 'DEL-NORTH',
      address: 'Northern Logistics & Showroom Hub',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110001',
      phone: '+91 XXX XXX XXXX',
      whatsapp: '917702256073',
      email: 'delhi@frostflow.com',
      coordinates: { lat: 28.5355, lng: 77.2732 },
      operatingHours: 'Mon - Sat: 9:00 AM - 7:00 PM',
      isMainBranch: false,
      servicesOffered: ['Heavy Commercial Freezers', 'Turnkey Cold Storage Planning'],
      createdAt: '2026-02-01T00:00:00.000Z',
      deletedAt: null,
    },
  ],
};

export const mockCategories: Category[] = [
  {
    id: 'cat-visi-coolers',
    tenantId: 'tenant-frostflow-01',
    slug: 'display-refrigerators',
    name: 'Display Refrigerators (Visi-Coolers)',
    description: 'Double & triple pane glass chillers designed for maximum beverage and dairy merchandising.',
    icon: 'Store',
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?q=80&w=800&auto=format&fit=crop',
    operatingTempBadge: '+1°C to +8°C',
    sortOrder: 1,
    deletedAt: null,
  },
  {
    id: 'cat-deep-freezers',
    tenantId: 'tenant-frostflow-01',
    slug: 'deep-freezers',
    name: 'Commercial Deep Freezers',
    description: 'Heavy duty hard-top and curved glass-top deep freezers with high-density cyclopentane insulation.',
    icon: 'Snowflake',
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?q=80&w=800&auto=format&fit=crop',
    operatingTempBadge: '-18°C to -25°C',
    sortOrder: 2,
    deletedAt: null,
  },
  {
    id: 'cat-ice-machines',
    tenantId: 'tenant-frostflow-01',
    slug: 'ice-machines',
    name: 'Commercial Ice Machines',
    description: 'Modular gourmet cube, bullet ice, and flaked ice makers for bars, hotels, and seafood displays.',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop',
    operatingTempBadge: '-10°C Ice Core',
    sortOrder: 3,
    deletedAt: null,
  },
  {
    id: 'cat-cold-rooms',
    tenantId: 'tenant-frostflow-01',
    slug: 'cold-storage',
    name: 'Modular Walk-in Cold Rooms',
    description: 'PUF panel walk-in chillers and blast storage solutions tailored for agro, meat, and pharma hubs.',
    icon: 'Box',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop',
    operatingTempBadge: '-30°C to +10°C',
    sortOrder: 4,
    deletedAt: null,
  },
  {
    id: 'cat-bakery-cases',
    tenantId: 'tenant-frostflow-01',
    slug: 'bakery-equipment',
    name: 'Bakery & Pastry Display Cases',
    description: 'Curved glass heated and refrigerated display counters with humidity balance to keep pastries fresh.',
    icon: 'Layers',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
    operatingTempBadge: '+2°C to +8°C (65% RH)',
    sortOrder: 5,
    deletedAt: null,
  },
  {
    id: 'cat-undercounter',
    tenantId: 'tenant-frostflow-01',
    slug: 'kitchen-equipment',
    name: 'Stainless Kitchen Undercounter Units',
    description: 'GN pan compatible stainless steel workbench chillers and salad prep stations for commercial kitchens.',
    icon: 'UtensilsCrossed',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=800&auto=format&fit=crop',
    operatingTempBadge: '-2°C to +8°C',
    sortOrder: 6,
    deletedAt: null,
  },
];

export const mockBrands: Brand[] = [
  {
    id: 'brand-voltas',
    tenantId: 'tenant-frostflow-01',
    slug: 'industrial-series',
    name: 'Heavy-Duty Industrial',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=200&auto=format&fit=crop',
    description: 'High-capacity commercial cooling solutions engineered for severe ambient conditions.',
    countryOfOrigin: 'Commercial Standard',
    warrantyPolicy: 'Standard Equipment Warranty (Customizable per Dealer)',
    isPopular: true,
    deletedAt: null,
  },
  {
    id: 'brand-western',
    tenantId: 'tenant-frostflow-01',
    slug: 'commercial-series',
    name: 'Commercial Series',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=200&auto=format&fit=crop',
    description: 'High-visibility glass showcase chillers built for retail merchandising and impulse beverage sales.',
    countryOfOrigin: 'Commercial Standard',
    warrantyPolicy: 'Standard Equipment Warranty (Customizable per Dealer)',
    isPopular: true,
    deletedAt: null,
  },
  {
    id: 'brand-bluestar',
    tenantId: 'tenant-frostflow-01',
    slug: 'modular-cold-chain',
    name: 'Modular Cold Chain',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=200&auto=format&fit=crop',
    description: 'Engineered modular PUF walk-in cold rooms, condensing units, and blast storage chillers.',
    countryOfOrigin: 'Commercial Standard',
    warrantyPolicy: 'Standard Equipment Warranty (Customizable per Dealer)',
    isPopular: true,
    deletedAt: null,
  },
  {
    id: 'brand-trufrost',
    tenantId: 'tenant-frostflow-01',
    slug: 'culinary-series',
    name: 'Culinary & Food Service',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=200&auto=format&fit=crop',
    description: 'Specialized bakery showcase displays, gourmet ice cubers, and stainless undercounter prep units.',
    countryOfOrigin: 'Commercial Standard',
    warrantyPolicy: 'Standard Equipment Warranty (Customizable per Dealer)',
    isPopular: true,
    deletedAt: null,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-arctic-visi-500',
    tenantId: 'tenant-frostflow-01',
    slug: 'arctic-pro-visi-cooler',
    name: 'ArcticPro Series Commercial Visi-Cooler',
    brandId: 'brand-western',
    categoryId: 'cat-visi-coolers',
    shortDescription: 'High-visibility double glazed glass door commercial chiller with dynamic forced air cooling.',
    description:
      'Engineered for supermarkets, retail cafes, and high-footfall beverage display. Equipped with self-closing Low-E heated glass doors, vertical full-length LED illumination, and an eco-friendly R290 hydrocarbon cooling circuit.',
    features: [
      'Self-closing Low-E double pane toughened glass door with anti-condensation heater',
      'High-velocity fan assisted dynamic cooling for uniform temperature across all shelves',
      'Illuminated customizable canopy for branding / logo promotion',
      'Digital microcomputer controller with LED temperature readout',
      'Heavy duty powder coated adjustable wire shelves (50 kg capacity per shelf)',
      'Heavy duty swivel castors with front brake locks',
    ],
    applications: ['Supermarkets & Hypermarkets', 'Convenience Stores', 'Beverage Boutiques', 'Restaurants & Cafes'],
    specifications: {
      'Refrigerant Gas': 'R290 Eco-Hydrocarbon (Zero ODP / Low GWP)',
      'Defrost Type': 'Automatic Off-Cycle Defrost',
      'Door Type': 'Self-Closing Double Glazed Low-E Glass',
      'Internal Lighting': 'Dual Vertical LED Strips (5000K Ice White)',
      'Temperature Controller': 'Carel / Dixell Digital Microprocessor',
      'Electrical Supply': '230V / 50Hz Single Phase',
      'Insulation': '60mm High-Density Cyclopentane PUF',
    },
    media: [
      {
        id: 'med-1',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-arctic-visi-500',
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Front View Double Glass Visi Cooler',
        altText: 'Commercial Visi Cooler Glass Showcase',
        sortOrder: 1,
        isPrimary: true,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'med-2',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-arctic-visi-500',
        url: 'https://images.unsplash.com/photo-1527011046414-4781f1f94f8c?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Shelving & Internal LED Illumination',
        altText: 'Internal display shelves',
        sortOrder: 2,
        isPrimary: false,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    variants: [
      {
        id: 'var-visi-350',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-arctic-visi-500',
        sku: 'FF-VC-350L',
        name: '350 Litre Single Door',
        capacity: '350L',
        dimensions: '595 × 640 × 1850 mm',
        powerConsumption: '2.4 kWh / 24h',
        temperatureRange: '+2°C to +8°C',
        basePrice: 42000,
        offerPrice: 38500,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-visi-500',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-arctic-visi-500',
        sku: 'FF-VC-500L',
        name: '500 Litre Single Door Max',
        capacity: '500L',
        dimensions: '680 × 700 × 1998 mm',
        powerConsumption: '3.1 kWh / 24h',
        temperatureRange: '+1°C to +8°C',
        basePrice: 54000,
        offerPrice: 49500,
        stockStatus: 'in_stock',
        isDefault: true,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-visi-1000',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-arctic-visi-500',
        sku: 'FF-VC-1000D',
        name: '1000 Litre Double Sliding Door',
        capacity: '1000L',
        dimensions: '1200 × 720 × 2020 mm',
        powerConsumption: '5.8 kWh / 24h',
        temperatureRange: '+1°C to +8°C',
        basePrice: 92000,
        offerPrice: 85000,
        stockStatus: 'low_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
    ],
    isFeatured: true,
    isNew: false,
    isOffer: true,
    seoTitle: 'Commercial Visi Cooler Refrigerator | 350L - 1000L Glass Door Showcases',
    seoDescription: 'Heavy-duty commercial visi-coolers with double Low-E glass, forced air cooling, and energy-saving R290 refrigerant. Instant B2B pricing and delivery.',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-glacier-chest-freezer',
    tenantId: 'tenant-frostflow-01',
    slug: 'glacier-commercial-chest-freezer',
    name: 'Glacier Heavy-Duty Commercial Deep Freezer',
    brandId: 'brand-voltas',
    categoryId: 'cat-chest-freezers',
    shortDescription: 'Industrial tropicalized chest freezer with ultra-thick PUF insulation and dual-temperature convertible mode.',
    description:
      'Designed specifically for tropical climates up to 43°C ambient temperature. Features a convertible thermostat (Freezer / Chiller), heavy-duty prepainted steel interior, lockable counter-balanced lid, and high-performance copper tube condenser.',
    features: [
      'Dual-Mode Convertible Thermostat: Switch easily between Deep Freezer (-18°C) and Chiller (+2°C)',
      '70mm High-Density Cyclopentane insulation holding temperature for up to 14 hours during power outages',
      'Embraco / Danfoss tropicalized commercial compressor',
      'Corrosion resistant embossed stucco aluminum inner liner',
      'Recessed door handles with key lock security',
      'Quick drain plug for effortless cleaning and manual defrosting',
    ],
    applications: ['Ice Cream Parlours', 'Frozen Food Distribution', 'Commercial Meat & Poultry Outlets', 'Cloud Kitchens'],
    specifications: {
      'Operating Mode': 'Convertible Dual Temp (Freezer / Cooler)',
      'Ambient Rating': 'Tropicalized up to +43°C Ambient',
      'Refrigerant': 'R134a / R290 Non-CFC',
      'Lid Construction': 'High-tensile spring counterbalanced solid top',
      'Compressor': 'Heavy duty commercial hermetic',
      'Holdover Time': 'Up to 14 Hours without electricity',
      'Warranty': 'Dealer-configurable (Standard Commercial Warranty)',
    },
    media: [
      {
        id: 'med-3',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-glacier-chest-freezer',
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Glacier Commercial Deep Freezer Solid Top',
        altText: 'Heavy Duty Deep Freezer',
        sortOrder: 1,
        isPrimary: true,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    variants: [
      {
        id: 'var-df-320',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-glacier-chest-freezer',
        sku: 'GL-DF-320L',
        name: '320 Litre Single Door',
        capacity: '320L',
        dimensions: '1120 × 660 × 850 mm',
        powerConsumption: '1.8 kWh / 24h',
        temperatureRange: '-18°C to -24°C',
        basePrice: 28500,
        offerPrice: 26200,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-df-500',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-glacier-chest-freezer',
        sku: 'GL-DF-500D',
        name: '500 Litre Double Door Commercial',
        capacity: '500L',
        dimensions: '1640 × 720 × 865 mm',
        powerConsumption: '2.8 kWh / 24h',
        temperatureRange: '-18°C to -25°C',
        basePrice: 43000,
        offerPrice: 39500,
        stockStatus: 'in_stock',
        isDefault: true,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-df-750',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-glacier-chest-freezer',
        sku: 'GL-DF-750T',
        name: '750 Litre Heavy Duty Triple Door',
        capacity: '750L',
        dimensions: '2080 × 760 × 890 mm',
        powerConsumption: '4.2 kWh / 24h',
        temperatureRange: '-18°C to -25°C',
        basePrice: 62000,
        offerPrice: 57500,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
    ],
    isFeatured: true,
    isNew: false,
    isOffer: true,
    seoTitle: 'Commercial Deep Freezers 320L to 750L | Heavy Duty Hard Top Storage',
    seoDescription: 'High performance tropicalized commercial deep freezers with dual temperature modes, fast pull-down, and 14-hour thermal holdover.',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-ice-cube-maker',
    tenantId: 'tenant-frostflow-01',
    slug: 'crystal-ice-cube-machine',
    name: 'CrystalPro Gourmet Commercial Ice Machine',
    brandId: 'brand-trufrost',
    categoryId: 'cat-ice-machines',
    shortDescription: 'Stainless steel automated gourmet dice ice maker with built-in storage bin and auto-sanitization.',
    description:
      'High capacity automated ice maker producing crystal-clear gourmet square dice cubes for restaurants, clubs, and hotel cocktail bars. Features air-cooled condenser, spray evaporator technology, and self-cleaning sanitization cycle.',
    features: [
      'Advanced spray system producing slow-melting, crystal clear gourmet ice cubes',
      'Front ventilation air-intake and exhaust for tight undercounter or back-bar installation',
      'Food-grade AgION antimicrobial interior protection preventing slime build-up',
      'Automatic harvest cycle and auto-shutoff when storage bin is full',
      'Stainless steel 304 external casing with fingerprint resistant coating',
    ],
    applications: ['Cocktail Bars & Lounges', 'Fine Dining Restaurants', 'Hotels & Banquets', 'Healthcare Facilities'],
    specifications: {
      'Ice Type': 'Gourmet Square Dice (22 × 22 × 22 mm)',
      'Condenser Cooling': 'Forced Air Cooled',
      'Water Connection': 'Standard 3/4" BSP inlet with in-line sediment filter',
      'Body Material': 'SUS 304 Stainless Steel',
      'Sanitization': 'One-Touch Automated Cleaning Cycle',
      'Warranty': '1 Year Full Unit On-Site Service',
    },
    media: [
      {
        id: 'med-4',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-ice-cube-maker',
        url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Commercial Stainless Ice Machine',
        altText: 'Crystal Ice Maker',
        sortOrder: 1,
        isPrimary: true,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    variants: [
      {
        id: 'var-ice-50',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-ice-cube-maker',
        sku: 'CP-ICE-50KG',
        name: '50 kg / 24h Undercounter (25 kg Bin)',
        capacity: '50 kg/day',
        dimensions: '500 × 580 × 800 mm',
        powerConsumption: '480 Watts',
        temperatureRange: '-10°C Ice Core',
        basePrice: 68000,
        offerPrice: 62000,
        stockStatus: 'in_stock',
        isDefault: true,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-ice-120',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-ice-cube-maker',
        sku: 'CP-ICE-120KG',
        name: '120 kg / 24h Modular (55 kg Bin)',
        capacity: '120 kg/day',
        dimensions: '660 × 680 × 1200 mm',
        powerConsumption: '850 Watts',
        temperatureRange: '-10°C Ice Core',
        basePrice: 115000,
        offerPrice: 104000,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-ice-250',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-ice-cube-maker',
        sku: 'CP-ICE-250KG',
        name: '250 kg / 24h Heavy Commercial Modular',
        capacity: '250 kg/day',
        dimensions: '760 × 850 × 1650 mm',
        powerConsumption: '1450 Watts',
        temperatureRange: '-10°C Ice Core',
        basePrice: 198000,
        offerPrice: 182000,
        stockStatus: 'contact_for_availability',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
    ],
    isFeatured: true,
    isNew: true,
    isOffer: false,
    seoTitle: 'Commercial Ice Cube Machines 50kg to 250kg | Bar & Restaurant Ice Makers',
    seoDescription: 'High output stainless steel commercial ice machines with crystal cube spray tech and automatic self-cleaning.',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-walkin-coldroom',
    tenantId: 'tenant-frostflow-01',
    slug: 'modular-puf-walk-in-cold-room',
    name: 'ThermaLock™ Modular Walk-in Cold Room System',
    brandId: 'brand-bluestar',
    categoryId: 'cat-cold-storage',
    shortDescription: 'Custom-engineered high-density PUF panel walk-in chillers and freezer rooms with remote condensing units.',
    description:
      'Complete turnkey cold room solution including high-efficiency PUF panels with cam-lock tongue-and-groove joints, heavy-duty insulated swing/sliding doors, microprocessor control panel with remote temperature telemetry, and Bitzer/Emerson scroll condensing units.',
    features: [
      'High-Density 40±2 kg/m³ CFC-free Polyurethane Foam (PUF) insulation panels',
      'Cam-Lock interlocking mechanism ensuring air-tight thermal envelope',
      'Anti-slip aluminum chequered floor panel with underfloor heater for sub-zero freezer applications',
      'High-humidity evaporators with stainless steel drain pan and electric defrost heaters',
      'Pressure relief valve and internal emergency safety door release handle',
      'Digital panel board with audio-visual high/low temperature alarm and data logger',
    ],
    applications: ['Central Food Production Hubs', 'Hospitals & Blood Banks', 'Supermarket Backrooms', 'Fruit & Dairy Logistics'],
    specifications: {
      'Panel Thickness': '60mm (Chiller) / 100mm (Freezer) / 150mm (Blast)',
      'Joint Type': 'Cam-Lock with PVC Gaskets',
      'Facing Material': '0.5mm Pre-painted Galvanized Steel (PPGI) / Stainless Steel 304',
      'Condensing Unit': 'Emerson Copeland Scroll / Bitzer Semi-Hermetic',
      'Safety Compliance': 'Internal glow-in-the-dark safety escape latch',
      'Warranty': 'Dealer-configurable (Standard Commercial Warranty)',
    },
    media: [
      {
        id: 'med-5',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-walkin-coldroom',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Industrial Walk-in Cold Room Installation',
        altText: 'Modular Cold Room',
        sortOrder: 1,
        isPrimary: true,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    variants: [
      {
        id: 'var-cr-10x10-chiller',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-walkin-coldroom',
        sku: 'TL-CR-1010-CH',
        name: '10×10×8 ft Modular Chiller (+2°C to +8°C)',
        capacity: '800 Cu.Ft (approx 22,000 Litres)',
        dimensions: '3048 × 3048 × 2438 mm',
        powerConsumption: '3.5 kW Connected Load',
        temperatureRange: '+2°C to +8°C',
        basePrice: 345000,
        offerPrice: 315000,
        stockStatus: 'in_stock',
        isDefault: true,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-cr-10x10-freezer',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-walkin-coldroom',
        sku: 'TL-CR-1010-FZ',
        name: '10×10×8 ft Modular Deep Freezer (-18°C to -22°C)',
        capacity: '800 Cu.Ft (approx 22,000 Litres)',
        dimensions: '3048 × 3048 × 2438 mm',
        powerConsumption: '5.2 kW Connected Load',
        temperatureRange: '-18°C to -22°C',
        basePrice: 420000,
        offerPrice: 385000,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-cr-custom',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-walkin-coldroom',
        sku: 'TL-CR-CUSTOM',
        name: 'Custom Sized Turnkey Cold Room Installation',
        capacity: 'Custom Engineered',
        dimensions: 'Custom Layout',
        powerConsumption: 'Site Engineered',
        temperatureRange: '-35°C to +15°C',
        basePrice: 550000,
        offerPrice: 499000,
        stockStatus: 'contact_for_availability',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
    ],
    isFeatured: true,
    isNew: false,
    isOffer: false,
    seoTitle: 'Walk-in Cold Rooms & PUF Freezers | Turnkey Commercial Cold Storage',
    seoDescription: 'High efficiency modular walk-in cold rooms with cam-lock PUF panels, scroll condensing units, and turnkey installation support.',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-bakery-curved-case',
    tenantId: 'tenant-frostflow-01',
    slug: 'panache-curved-bakery-display',
    name: 'Panache Curved Glass Refrigerated Bakery Showcase',
    brandId: 'brand-trufrost',
    categoryId: 'cat-bakery-cases',
    shortDescription: 'Luxury curved panoramic glass pastry and cake chiller with controlled humidity and warm LED illumination.',
    description:
      'Designed to elevate confectionery and pastry presentation. Featuring heated front glass to eliminate condensation, rear sliding double-glazed service doors, 3 tier adjustable glass shelves with individual warm LED illumination, and gentle laminar airflow that preserves cake moisture.',
    features: [
      'Heated curved front glass eliminating condensation in high humidity',
      'Gentle laminar cooling system preventing drying out of delicate pastries and desserts',
      '3-Tier tempered glass shelves with warm 3000K food-presentation LED lights',
      'Rear double-glazed sliding mirror doors for effortless staff loading',
      'Black mirror stainless steel base cladding for premium European aesthetic',
    ],
    applications: ['Artisan Bakeries', 'Pastry & Dessert Boutiques', 'Specialty Coffee Roasters', 'Hotel Delis'],
    specifications: {
      'Glass Type': 'Panoramic Heated Curved Front Glass',
      'Humidity Control': 'Gentle Air Circulation (65% to 75% Relative Humidity)',
      'Shelves': '3 Levels Adjustable Heavy Duty Glass',
      'Refrigerant': 'R134a / R290 Non-CFC',
      'Temperature Range': '+2°C to +8°C',
      'Base Finish': 'Titanium Black Mirror Stainless Steel',
    },
    media: [
      {
        id: 'med-6',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-bakery-curved-case',
        url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Pastry & Cake Display Showcase',
        altText: 'Bakery Display Showcase',
        sortOrder: 1,
        isPrimary: true,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    variants: [
      {
        id: 'var-bakery-3ft',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-bakery-curved-case',
        sku: 'PN-BK-3FT',
        name: '3 Feet (900 mm) Compact Pastry Case',
        capacity: '320L',
        dimensions: '900 × 750 × 1350 mm',
        powerConsumption: '650 Watts',
        temperatureRange: '+2°C to +8°C',
        basePrice: 78000,
        offerPrice: 72000,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-bakery-4ft',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-bakery-curved-case',
        sku: 'PN-BK-4FT',
        name: '4 Feet (1200 mm) Standard Bakery Showcase',
        capacity: '460L',
        dimensions: '1200 × 750 × 1350 mm',
        powerConsumption: '850 Watts',
        temperatureRange: '+2°C to +8°C',
        basePrice: 96000,
        offerPrice: 88000,
        stockStatus: 'in_stock',
        isDefault: true,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-bakery-5ft',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-bakery-curved-case',
        sku: 'PN-BK-5FT',
        name: '5 Feet (1500 mm) Grand Pastry Showcase',
        capacity: '600L',
        dimensions: '1500 × 750 × 1350 mm',
        powerConsumption: '1050 Watts',
        temperatureRange: '+2°C to +8°C',
        basePrice: 118000,
        offerPrice: 108000,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
    ],
    isFeatured: false,
    isNew: true,
    isOffer: true,
    seoTitle: 'Heated Glass Bakery Display Counters | Pastry & Cake Refrigerated Cases',
    seoDescription: 'Premium curved glass refrigerated bakery showcases with anti-condensation heated front glass and moisture-retention cooling.',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-undercounter-workbench',
    tenantId: 'tenant-frostflow-01',
    slug: 'commercial-stainless-undercounter-chiller',
    name: 'ChefPro Heavy-Duty Stainless Undercounter Chiller',
    brandId: 'brand-voltas',
    categoryId: 'cat-undercounter',
    shortDescription: 'All-stainless steel GN 1/1 compatible refrigerated workbench with heavy-duty prep table top.',
    description:
      'The workhorse of professional commercial kitchens. Constructed from high-grade AISI 304 food-contact stainless steel with rounded internal hygienic corners, self-closing solid stainless doors, and ventilated forced refrigeration designed for grueling commercial line service.',
    features: [
      'Full AISI 304 food-grade stainless steel interior and heavy duty workbench exterior',
      'Standard Gastronorm GN 1/1 pan compatible tray slide runners',
      '50mm thick heavy gauge stainless steel tabletop for ingredient prep and tabletop appliances',
      'Removable magnetic door gaskets for rapid cleaning and sanitary compliance',
      'Electronic digital thermostat with automatic defrost cycle',
      'Adjustable heavy-duty stainless steel bullet feet (+/- 50mm leveling)',
    ],
    applications: ['Commercial Hotel Kitchens', 'Pizzeria Prep Counters', 'Burger Chains & Quick Service', 'Catering Facilities'],
    specifications: {
      'Construction': 'SUS 304 Food-Grade Stainless Steel (1.0mm thickness)',
      'Tray Compatibility': 'Standard Gastronorm GN 1/1 Trays',
      'Insulation': '50mm High-Density Injected Cyclopentane',
      'Door Type': 'Self-closing Solid Stainless Doors with 90° stay-open feature',
      'Temperature Range': '-2°C to +8°C',
      'Refrigerant': 'R290 Hydrocarbon',
    },
    media: [
      {
        id: 'med-7',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-undercounter-workbench',
        url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=1000&auto=format&fit=crop',
        type: 'image',
        title: 'Stainless Steel Workbench Chiller',
        altText: 'Undercounter Stainless Chiller',
        sortOrder: 1,
        isPrimary: true,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    variants: [
      {
        id: 'var-uc-2door',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-undercounter-workbench',
        sku: 'CP-UC-2D',
        name: '2-Door Workbench (280 Litre / 1200mm)',
        capacity: '280L',
        dimensions: '1200 × 700 × 850 mm',
        powerConsumption: '320 Watts',
        temperatureRange: '-2°C to +8°C',
        basePrice: 58000,
        offerPrice: 52500,
        stockStatus: 'in_stock',
        isDefault: true,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
      {
        id: 'var-uc-3door',
        tenantId: 'tenant-frostflow-01',
        productId: 'prod-undercounter-workbench',
        sku: 'CP-UC-3D',
        name: '3-Door Heavy Workbench (420 Litre / 1800mm)',
        capacity: '420L',
        dimensions: '1800 × 700 × 850 mm',
        powerConsumption: '450 Watts',
        temperatureRange: '-2°C to +8°C',
        basePrice: 78000,
        offerPrice: 71000,
        stockStatus: 'in_stock',
        isDefault: false,
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        deletedAt: null,
      },
    ],
    isFeatured: true,
    isNew: false,
    isOffer: false,
    seoTitle: 'Commercial Stainless Undercounter Chillers | 2 & 3 Door Worktop Refrigerators',
    seoDescription: 'Heavy-duty AISI 304 stainless steel undercounter chillers and prep tables for commercial restaurant kitchens.',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    tenantId: 'tenant-frostflow-01',
    name: 'Rajesh Sharma',
    businessName: 'Royal Grand Hotel & Banquets',
    customerType: 'hotel_restaurant',
    phone: '+91 98201 11223',
    whatsapp: '919820111223',
    email: 'purchasing@royalgrand.in',
    city: 'Mumbai',
    address: 'Juhu Beach Road, Mumbai',
    gstNumber: '27AABCR1234F1Z1',
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-02-10T10:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'cust-2',
    tenantId: 'tenant-frostflow-01',
    name: 'Vikram Mehta',
    businessName: 'Urban Artisan Bakery Chain',
    customerType: 'contractor',
    phone: '+91 98451 99887',
    whatsapp: '919845199887',
    email: 'vikram@urbanartisan.com',
    city: 'Bengaluru',
    address: 'Indiranagar 100ft Road, Bengaluru',
    gstNumber: '29AACCM9876E1Z5',
    createdAt: '2026-02-14T14:30:00.000Z',
    updatedAt: '2026-02-14T14:30:00.000Z',
    deletedAt: null,
  },
  {
    id: 'cust-3',
    tenantId: 'tenant-frostflow-01',
    name: 'Ananya Deshmukh',
    businessName: 'FreshHarvest Supermarkets',
    customerType: 'enterprise',
    phone: '+91 98112 44556',
    whatsapp: '919811244556',
    email: 'ananya@freshharvest.co',
    city: 'New Delhi',
    address: 'Plot 18, Commercial Hub, Noida',
    gstNumber: '07AAACD5544B1Z8',
    createdAt: '2026-02-20T09:15:00.000Z',
    updatedAt: '2026-02-20T09:15:00.000Z',
    deletedAt: null,
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'lead-101',
    tenantId: 'tenant-frostflow-01',
    customerId: 'cust-1',
    branchId: 'branch-mumbai-hq',
    source: 'website',
    inquiryType: 'product',
    productId: 'prod-arctic-visi-500',
    variantId: 'var-visi-1000',
    message: 'Need 4 units of 1000L double door visi coolers for banquet hall beverage station. Urgent delivery required by Friday.',
    status: 'contacted',
    assignedStaff: 'Vikram (Senior Sales Engineer)',
    activities: [
      {
        id: 'act-1',
        tenantId: 'tenant-frostflow-01',
        leadId: 'lead-101',
        type: 'lead_created',
        description: 'Customer submitted product inquiry on website for 1000L Visi-Coolers.',
        timestamp: '2026-02-22T09:30:00.000Z',
      },
      {
        id: 'act-2',
        tenantId: 'tenant-frostflow-01',
        leadId: 'lead-101',
        type: 'whatsapp',
        description: 'Sent commercial spec sheet and stock verification via WhatsApp.',
        performedBy: 'Vikram',
        timestamp: '2026-02-22T09:45:00.000Z',
      },
      {
        id: 'act-3',
        tenantId: 'tenant-frostflow-01',
        leadId: 'lead-101',
        type: 'note',
        description: 'Customer requires site delivery with hydraulic tail-lift vehicle. Advance payment ready.',
        performedBy: 'Vikram',
        timestamp: '2026-02-22T11:15:00.000Z',
      },
    ],
    createdAt: '2026-02-22T09:30:00.000Z',
    updatedAt: '2026-02-22T11:15:00.000Z',
    deletedAt: null,
  },
  {
    id: 'lead-102',
    tenantId: 'tenant-frostflow-01',
    customerId: 'cust-2',
    branchId: 'branch-blr-hub',
    source: 'whatsapp',
    inquiryType: 'service',
    productId: 'prod-bakery-curved-case',
    message: 'Opening 2 new bakery outlets in Koramangala. Need 4ft curved pastry counters and installation support.',
    status: 'qualified',
    assignedStaff: 'Priya (Project Consultant)',
    activities: [
      {
        id: 'act-4',
        tenantId: 'tenant-frostflow-01',
        leadId: 'lead-102',
        type: 'lead_created',
        description: 'WhatsApp inquiry routed through Koramangala showroom link.',
        timestamp: '2026-02-23T14:10:00.000Z',
      },
      {
        id: 'act-5',
        tenantId: 'tenant-frostflow-01',
        leadId: 'lead-102',
        type: 'call',
        description: 'Telephonic site assessment with interior architect completed.',
        performedBy: 'Priya',
        timestamp: '2026-02-23T16:00:00.000Z',
      },
    ],
    createdAt: '2026-02-23T14:10:00.000Z',
    updatedAt: '2026-02-23T16:00:00.000Z',
    deletedAt: null,
  },
];

export const mockQuoteRequests: QuoteRequest[] = [
  {
    id: 'QR-2026-00381',
    tenantId: 'tenant-frostflow-01',
    customerId: 'cust-3',
    branchId: 'branch-delhi-ncr',
    items: [
      {
        productId: 'prod-glacier-chest-freezer',
        variantId: 'var-df-500',
        quantity: 6,
      },
      {
        productId: 'prod-arctic-visi-500',
        variantId: 'var-visi-500',
        quantity: 4,
      },
    ],
    installationRequired: true,
    amcRequired: true,
    deliveryCity: 'Noida',
    siteConstraints: 'Ground floor supermarket setup, 3-phase stabilized line ready.',
    notes: 'Please quote institutional bulk discount and include 1-year AMC maintenance.',
    status: 'converted_to_quote',
    createdAt: '2026-02-24T11:00:00.000Z',
    updatedAt: '2026-02-24T12:30:00.000Z',
    deletedAt: null,
  },
];

export const mockQuotes: Quote[] = [
  {
    id: 'QT-2026-00482',
    quoteRequestId: 'QR-2026-00381',
    tenantId: 'tenant-frostflow-01',
    customerId: 'cust-3',
    branchId: 'branch-delhi-ncr',
    version: 1,
    lineItems: [
      {
        productId: 'prod-glacier-chest-freezer',
        variantId: 'var-df-500',
        sku: 'GL-DF-500D',
        productName: 'Glacier Heavy-Duty Commercial Deep Freezer',
        variantName: '500 Litre Double Door Commercial',
        unitPrice: 39500,
        discountPercentage: 8,
        discountedUnitPrice: 36340,
        quantity: 6,
        totalPrice: 218040,
      },
      {
        productId: 'prod-arctic-visi-500',
        variantId: 'var-visi-500',
        sku: 'FF-VC-500L',
        productName: 'ArcticPro Series Commercial Visi-Cooler',
        variantName: '500 Litre Single Door Max',
        unitPrice: 49500,
        discountPercentage: 8,
        discountedUnitPrice: 45540,
        quantity: 4,
        totalPrice: 182160,
      },
    ],
    subtotal: 435000,
    totalDiscount: 34800,
    installationFee: 15000,
    deliveryFee: 8000,
    amcFee: 24012,
    taxRate: 0.18,
    taxAmount: 80498,
    grandTotal: 527710,
    validUntil: '2026-03-15',
    termsAndConditions: [
      '50% Advance with Purchase Order, 50% prior to dispatch.',
      'Delivery timeline: 3-5 business days from confirmed order date.',
      'Includes dealer-configurable commercial warranty terms.',
      'Onsite commissioning and operational staff demo included.',
    ],
    status: 'sent',
    assignedStaff: 'Demo Sales Desk',
    createdAt: '2026-02-24T12:30:00.000Z',
    updatedAt: '2026-02-24T12:30:00.000Z',
    deletedAt: null,
  },
];

export const mockFAQs: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Commercial Delivery & Shipping',
    question: 'How fast can commercial refrigeration units be dispatched?',
    answer:
      'Standard catalog models available at regional showrooms are dispatched within 24 to 48 hours. Custom turnkey cold rooms and modular systems require 5 to 10 days for site engineering.',
  },
  {
    id: 'faq-2',
    category: 'Power & Electrical Requirements',
    question: 'What electrical supply and stabilizer setup is recommended?',
    answer:
      'Standard plug-in units operate on standard 230V / 50Hz single-phase supply with a 15A/16A industrial socket. Large walk-in cold rooms require 415V 3-phase stabilized supply.',
  },
  {
    id: 'faq-3',
    category: 'B2B Quotation & Volume Discounts',
    question: 'How do tiered commercial volume discounts work?',
    answer:
      'Commercial pricing automatically factors in order volumes: 3-5 units get 5% discount, 6-9 units receive 8%, and 10+ units get 12% bulk discount. Tailored contract rates are generated via the B2B quote cart.',
  },
  {
    id: 'faq-4',
    category: 'Warranty & AMC Servicing',
    question: 'What warranty coverage is included with commercial units?',
    answer:
      'All commercial cooling appliances include dealer-configurable warranty coverage. Annual Maintenance Contracts (AMC) with scheduled preventive quarterly maintenance are also supported.',
  },
];

export const mockTestimonials: Testimonial[] = [];

export const mockGallery: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Flagship Mumbai Refrigeration Experience Center',
    category: 'Showroom',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=1000&auto=format&fit=crop',
    description: 'Interactive showroom with over 60 live commercial refrigeration display models.',
  },
  {
    id: 'gal-2',
    title: 'Supermarket Multi-Deck Chiller Line Installation',
    category: 'Supermarket',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?q=80&w=1000&auto=format&fit=crop',
    description: 'Turnkey beverage and dairy wall installation for 12,000 sq.ft hypermarket.',
  },
  {
    id: 'gal-3',
    title: 'Modular Cold Room for Pharmaceutical Logistics',
    category: 'Cold Room',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1000&auto=format&fit=crop',
    description: '+2°C to +8°C temperature validated cold room with dual redundant cooling circuits.',
  },
  {
    id: 'gal-4',
    title: 'Boutique Patisserie Curved Counter Showcase',
    category: 'Bakery & Cafe',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000&auto=format&fit=crop',
    description: 'Heated glass bakery showcases installed in luxury Bengaluru cafe.',
  },
];

export const mockOffers: OfferItem[] = [
  {
    id: 'off-1',
    title: 'Commercial Summer Cooling Upgrade Promo',
    code: 'COOLPROMO8',
    discountLabel: '8% OFF ON 3+ UNITS',
    description: 'Special seasonal pricing on all Visi-Coolers and Double-Door Deep Freezers with complimentary first-year preventive service.',
    expiryDate: '2026-04-30',
    applicableCategory: 'cat-visi-coolers',
  },
  {
    id: 'off-2',
    title: 'Turnkey Cold Room Installation Package',
    code: 'COLDSETUP',
    discountLabel: 'FREE SITE COMMISSIONING',
    description: 'Free technical site survey, digital temperature datalogger, and free installation on all walk-in modular PUF cold rooms.',
    expiryDate: '2026-05-15',
    applicableCategory: 'cat-cold-storage',
  },
];

export const mockIndustries: IndustryItem[] = [
  {
    id: 'ind-restaurants',
    slug: 'restaurants-cafes',
    name: 'Restaurants & Cloud Kitchens',
    icon: 'Utensils',
    tagline: 'High-Velocity Line Refrigeration & Food Safety Compliance',
    description:
      'Gastronorm stainless prep counters, heavy-duty undercounter chillers, blast freezers, and ice machines engineered for grueling commercial kitchen line speeds.',
    recommendedProducts: ['prod-undercounter-workbench', 'prod-ice-cube-maker', 'prod-arctic-visi-500'],
    caseStudy: {
      client: 'CloudBite 14-Location Kitchen Network',
      metrics: '34% Lower Energy Draw & Zero Spoilage',
      summary: 'Equipped complete kitchen footprints with SUS 304 GN prep counters and automated ice systems.',
    },
  },
  {
    id: 'ind-supermarkets',
    slug: 'supermarkets-retail',
    name: 'Supermarkets & Hypermarkets',
    icon: 'Store',
    tagline: 'Maximum Product Merchandising & Impulse Beverage Display',
    description:
      'Panoramic glass-door visi coolers, island chest freezers, multi-deck open chillers, and walk-in backroom inventory storage.',
    recommendedProducts: ['prod-arctic-visi-500', 'prod-glacier-chest-freezer', 'prod-walkin-coldroom'],
    caseStudy: {
      client: 'FreshBasket Hypermarket Chain',
      metrics: '48hr Emergency Hotline & 100% Uptime',
      summary: 'Installed 40+ glass display coolers and dual-temp backroom cold storage rooms.',
    },
  },
  {
    id: 'ind-bakeries',
    slug: 'bakeries-confectionery',
    name: 'Bakeries & Patisseries',
    icon: 'Cake',
    tagline: 'Precision Humidity Control & Crystal Curved Glass Presentation',
    description:
      'Anti-condensation heated glass display showcases, chocolate temper cabinets, and dough retarding proofing systems.',
    recommendedProducts: ['prod-bakery-curved-case', 'prod-undercounter-workbench'],
    caseStudy: {
      client: 'Le Petit Gateau Artisanal Bakery',
      metrics: '72hr Cake Moisture Preservation',
      summary: 'Custom titanium black mirror curved glass showcases maintaining 68% relative humidity.',
    },
  },
  {
    id: 'ind-cold-chain',
    slug: 'cold-storage-logistics',
    name: 'Cold Chain Logistics & Warehouses',
    icon: 'Warehouse',
    tagline: 'Heavy Industrial PUF Thermal Envelopes & Blast Storage',
    description:
      'Turnkey modular cold rooms, deep freeze holding rooms (-25°C), and blast chillers with remote IoT temperature logging.',
    recommendedProducts: ['prod-walkin-coldroom', 'prod-glacier-chest-freezer'],
    caseStudy: {
      client: 'Apex Agro Cold Logistics',
      metrics: '14hr Power Loss Thermal Holdover',
      summary: 'Engineered 100mm PUF freezer rooms with Bitzer scroll compressors.',
    },
  },
];

export const mockServices: ServiceItem[] = [
  {
    id: 'serv-cold-room',
    slug: 'cold-room-turnkey-installation',
    name: 'Turnkey Cold Room Design & Installation',
    icon: 'Warehouse',
    shortDescription: 'Custom engineering, PUF panel fabrication, and commissioning for commercial walk-in chillers and freezers.',
    fullDescription:
      'End-to-end cold storage execution from thermal load calculation and CAD layouts to PUF tongue-and-groove panel erection, scroll condensing unit installation, refrigerant charging, and digital telemetry setup.',
    features: [
      'Site thermal load heat-gain calculation and equipment sizing',
      'Air-tight Cam-Lock PUF panel assembly with aluminum coving',
      'Remote condenser piping with vibration dampeners and oil separators',
      'Digital microcomputer panel with audio-visual high temp alerts',
    ],
    pricingGuideline: 'Starting from ₹3,15,000 for standard 10×10ft chiller modules.',
    sla: 'Site survey within 24 hours | Turnkey completion in 5-7 business days.',
  },
  {
    id: 'serv-amc',
    slug: 'annual-maintenance-contract',
    name: 'Annual Maintenance Contracts (AMC)',
    icon: 'Wrench',
    shortDescription: 'Scheduled quarterly preventive servicing, chemical coil cleaning, and guaranteed priority breakdown response.',
    fullDescription:
      'Ensure 100% cooling uptime and lower power consumption. Our comprehensive AMC coverage covers coil cleaning, electrical terminal checkup, refrigerant pressure testing, thermostat calibration, and fast component replacement.',
    features: [
      '4 Scheduled quarterly preventive checkups with chemical condenser foam wash',
      'Guaranteed 4-hour breakdown emergency technician arrival in metro locations',
      'Discounted genuine manufacturer spare parts (compressors, fan motors, gaskets)',
      'Free loaner machine support during major workshop overhauls',
    ],
    pricingGuideline: 'Standard AMC plans at 6% to 8% of equipment invoice value per year.',
    sla: 'Guaranteed 4-Hour Response in Metro Showroom Zones.',
  },
  {
    id: 'serv-repair',
    slug: 'commercial-refrigeration-repair',
    name: 'Emergency Commercial Repair & Servicing',
    icon: 'ShieldCheck',
    shortDescription: '24/7 on-site emergency repair for gas leakage, compressor failure, electrical trips, and thermostat recalibration.',
    fullDescription:
      'Equipped with mobile service vans carrying genuine compressors, R290/R134a/R404a refrigerants, and electronic diagnostics to resolve critical cooling failures on first visit.',
    features: [
      '24/7 emergency dispatch line for restaurant and cold chain clients',
      'Nitrogen pressure testing and electronic ultrasonic leak detection',
      'Hermetic and semi-hermetic compressor retrofitting and oil flushing',
      'Replacement door gaskets and anti-sweat glass door heaters',
    ],
    pricingGuideline: '₹1,500 inspection visit fee (waived upon job approval) + parts.',
    sla: 'Dispatched within 2 hours of emergency call.',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'aud-1',
    tenantId: 'tenant-frostflow-01',
    userId: 'usr-admin-1',
    userName: 'Vikram Mehta (Manager)',
    action: 'status_change',
    entity: 'quote',
    entityId: 'QT-2026-00482',
    before: { status: 'draft' },
    after: { status: 'sent', grandTotal: 527710 },
    timestamp: '2026-02-24T12:30:00.000Z',
  },
  {
    id: 'aud-2',
    tenantId: 'tenant-frostflow-01',
    userId: 'usr-admin-1',
    userName: 'Vikram Mehta (Manager)',
    action: 'update',
    entity: 'product',
    entityId: 'prod-arctic-visi-500',
    before: { 'variants[1].offerPrice': 51000 },
    after: { 'variants[1].offerPrice': 49500 },
    timestamp: '2026-02-24T10:15:00.000Z',
  },
];
